### UGNX二次开发 创建香蕉形状的曲线网格 UF_MODL_create_thru_curves

#### 代码

```cpp
#include "me.hpp"
#include <stdarg.h>
#include <stdio.h>
#include <uf.h>
#include <uf_ui_types.h>
#include <uf_ui.h>

void  里海_科瑞特布呐呐(tag_t& tagBody);

extern DllExport void ufusr(char* parm, int* returnCode, int rlen)
{
    UF_initialize();
    tag_t tagBody = NULL_TAG;
    里海_科瑞特布呐呐(tagBody);
    UF_terminate();
}

extern int ufusr_ask_unload(void)
{
    return(UF_UNLOAD_IMMEDIATELY);
}

// 创建香蕉形状的曲线网格
void  里海_科瑞特布呐呐(tag_t &tagBody)
{
    vector<UF_CURVE_line_t> vecLineCoords(12);
    //里海：通过控制直线端点位置控制 香蕉形状
    vecLineCoords[0] = { {0.0,0.0,0.0},{0.0,1.0,0.0} };
    vecLineCoords[1] = { {0.0,0.0,0.0},{1.0,0.0,0.0} };
    vecLineCoords[2] = { {1.0,1.0,0.0},{0.0,1.0,0.0} };
    vecLineCoords[3] = { {1.0,1.0,0.0},{1.0,0.0,0.0} };

    vecLineCoords[4] = { {3.0,3.0,25.0},{0.0,10.0,25.0} };
    vecLineCoords[5] = { {3.0,3.0,25.0},{10.0,0.0,25.0} };
    vecLineCoords[6] = { {10.0,10.0,25.0},{0.0,10.0,25.0} };
    vecLineCoords[7] = { {10.0,10.0,25.0},{10.0,0.0,25.0} };

    vecLineCoords[8] = { {0.0,0.0,50.0},{0.0,1.0,50.0} };
    vecLineCoords[9] = { {0.0,0.0,50.0},{1.0,0.0,50.0} };
    vecLineCoords[10] = { {1.0,1.0,50.0},{0.0,1.0,50.0} };
    vecLineCoords[11] = { {1.0,1.0,50.0},{1.0,0.0,50.0} };

    UF_STRING_t sSection;
    UF_MODL_init_string_list(&sSection);
    UF_MODL_create_string_list(3, 12, &sSection); // 曲线组数 曲线对象数量
    for (int i = 0; i < vecLineCoords.size(); ++i)
    {
        tag_t tagLine = NULL_TAG;
        UF_CURVE_create_line(&vecLineCoords[i], &tagLine);
        sSection.id[i] = tagLine;
    }

    sSection.string[0] = 4;
    sSection.dir[0] = 1;
    sSection.string[1] = 4;
    sSection.dir[1] = 1;
    sSection.string[2] = 4;
    sSection.dir[2] = 1;

    UF_STRING_t sSpine;
    UF_MODL_init_string_list(&sSpine);

    int  patch = 1;
    int alignment = 1;
    double tol[3] = { 0, 0, 0 };
    double value[6] = { 0,0,0, 0,0,0 };
    int vdegree = 3;
    int vstatus = 0;
    int body_type = UF_MODL_SOLID_BODY;
    tag_t c_face[2] = { NULL_TAG, NULL_TAG };
    int c_flag[2] = { 0,0 };
    //里海：创建网格曲面
    UF_MODL_create_thru_curves(&sSection, &sSpine, &patch,
        &alignment, value, &vdegree, &vstatus, &body_type, UF_NULLSIGN,
        tol, c_face, c_flag, &tagBody);

    //如果不喜欢黄色的香蕉可以在这里修改成其他颜色
    int iYellowColor = 6; 
    UF_OBJ_set_color(tagBody, iYellowColor);

;    UF_MODL_free_string_list(&sSection);
    UF_MODL_free_string_list(&sSpine);
}

```

#### 代码解析
> 未找到解析内容

