### UGNX二次开发 获取面上距离点最近的边

#### 代码

```cpp
#include "me.hpp"


//获取对象到某个坐标的距离 
//原文链接：https ://blog.csdn.net/WangPaiFeiXingYuan/article/details/129776668
double getMinimumDis3(tag_t tagObj, double douGuess2[3])
{
    tag_t tagObj1 = tagObj;
    tag_t tagObj2 = NULL_TAG; //为空
    int iGuess2Given = 1; // 为1
    //double douGuess2[3] //设置点坐标
    double douDis = 0.0;
    double douPointOnObj1[3] = { 0 };
    double douPointOnObj2[3] = { 0 };
    double douAccuracy = 0.0;

    UF_MODL_ask_minimum_dist_3(2, tagObj1, tagObj2, 0, NULL,
        iGuess2Given, douGuess2, &douDis, douPointOnObj1, douPointOnObj2,
        &douAccuracy);

    //将两个对象上的点连接成一条直线
    UF_CURVE_line_t line_coords;
    UF_VEC3_copy(douPointOnObj1, line_coords.start_point);
    UF_VEC3_copy(douPointOnObj2, line_coords.end_point);
    tag_t tagLine = NULL_TAG;
    UF_CURVE_create_line(&line_coords, &tagLine);

    return douDis;
}
 

int GetFaceEdges(tag_t tagFace, vector<tag_t> &vecEdges)
{
	uf_list_p_t list1 = NULL;
	UF_MODL_create_list(&list1);
	UF_MODL_ask_face_edges(tagFace, &list1);
	int count = 0;
	UF_MODL_ask_list_count(list1, &count);
	for (int i = 0; i < count; i++)
	{
		tag_t tagEdge = NULL_TAG;
		UF_MODL_ask_list_item(list1, i, &tagEdge); 
		vecEdges.push_back(tagEdge);
	}
	UF_free(list1);
	list1 = NULL;
	return 0;
}


tag_t GetEdge(tag_t face, double point[])
{
    vector<tag_t> vecEdges;
    GetFaceEdges(face, vecEdges);

    tag_t tagEdge = NULL_TAG;
    double minDis = DBL_MAX;
    for (auto edge : vecEdges)
    {
        double dis = getMinimumDis3(edge, point);
        if (dis < minDis)
        {
            minDis = dis;
            tagEdge = edge;
        }
    }
	return tagEdge;
}


extern DllExport void ufusr(char* parm, int* returnCode, int rlen)
{
	UF_initialize();

	tag_t face = selectFace();

	char sCA[] = "点";
	UF_UI_POINT_base_method_t base_method = UF_UI_POINT_INFERRED;
	tag_t tagPoint = NULL_TAG;
	double douBasePoint[3] = { 0.0 };
	int iRes;
	UF_UI_point_construct(sCA, &base_method, &tagPoint, douBasePoint, &iRes);

	tag_t tagP = NULL_TAG;
	UF_CURVE_create_point(douBasePoint, &tagP);

	tag_t edge = GetEdge(face, douBasePoint);
	UF_DISP_set_highlight(edge, 1);
	uc1601("距离点最近的边已经高亮，点击确定取消高亮", 1);
	UF_DISP_set_highlight(edge, 0);

	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return(UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

