### 【UG二次开发】获取边的端点 UF_MODL_ask_edge_verts

#### 代码

```cpp
extern DllExport void ufsta(char *param, int *returnCode, int rlen)
{
    UF_initialize();
    tag_t tagEdge = 0;
    int vertex;
    double p1[3] = { 0.0, 0.0, 0.0 };
    double p2[3] = { 0.0, 0.0, 0.0 };
    UF_MODL_ask_edge_verts(tagEdge, p1, p2, &vertex);

    tag_t tagPointTemp;
    switch (vertex)
    {
    case 0:
        //这条边没有端点
        break;

    case 1:
        //这条有1个端点
        UF_CURVE_create_point(p1, &tagPointTemp);
        break;

    case 2:
        //这条有2个端点
        UF_CURVE_create_point(p1, &tagPointTemp);
        UF_CURVE_create_point(p2, &tagPointTemp);
        break;

    default:
        break;
    }
    UF_terminate();
}

extern int ufusr_ask_unload(void)
{
    return (UF_UNLOAD_IMMEDIATELY);
}
```

```cpp
int get_Edge_Start_Point(tag_t tagCurve, double douStol, double douStartPoint[3], double douEndPoint[3])
{
    double ctol(0.0);
    double atol(0.0);
    double stol(douStol);
    int numpts(0);
    tag_t pt_tag(NULL_TAG);

    double *ufPts = NULL;
    UF_MODL_ask_curve_points(tagCurve, ctol, atol, stol, &numpts, &ufPts);
    

    if (numpts >= 2)
    {
        douStartPoint[0] = ufPts[0];
        douStartPoint[1] = ufPts[1];
        douStartPoint[2] = ufPts[2];

        douEndPoint[0] = ufPts[0 + (numpts-1) * 3];
        douEndPoint[1] = ufPts[1 + (numpts-1) * 3];
        douEndPoint[2] = ufPts[2 + (numpts-1) * 3];

        tag_t tPointEnd = NULL_TAG;
        
        //UF_CURVE_create_point(douStartPoint, &tPointEnd);
        //UF_CURVE_create_point(douEndPoint, &tPointEnd);
    }
    else
    {
        return 1;
    }


    UF_free(ufPts);
    return 0;
}
```

```cpp
UF_CURVE_line_t EdgeStartEndPoint;
UF_CURVE_ask_line_data(tagEdge, &EdgeStartEndPoint);
//EdgeStartEndPoint.start_point
//EdgeStartEndPoint.end_point
```

#### 代码解析
> 未找到解析内容

