### UGNX 二次开发 获取实体面的面积，测量面积

#### 代码

```cpp
#include "me.hpp"

using namespace std;
using namespace NXOpen;


int init_proc_face0(UF_UI_selection_p_t select, void* user_data)
{
	int num_triples = 1;
	UF_UI_mask_t mask_triples[] = { UF_face_type,0,0 };
	if (UF_UI_set_sel_mask(select, UF_UI_SEL_MASK_CLEAR_AND_ENABLE_SPECIFIC, num_triples, mask_triples) == 0)
	{
		return (UF_UI_SEL_SUCCESS);
	}
	return (UF_UI_SEL_FAILURE);
}

tag_t SelectFace0()
{
	tag_t tagFace = NULL_TAG;
	int iReturn = 0;
	int iSelResp = 0;
	double pDblCursorPosTemp[3];
	tag_t tagViewTemp;
	tag_t pTagObjs;
	iReturn = UF_UI_select_with_single_dialog("请选择面", "请选择面", UF_UI_SEL_SCOPE_ANY_IN_ASSEMBLY,
		init_proc_face0, NULL, &iSelResp, &pTagObjs, pDblCursorPosTemp, &tagViewTemp);

	UF_CALL(iReturn);
	if (!iReturn && pTagObjs != NULL_TAG)
	{
		tagFace = pTagObjs;
		UF_DISP_set_highlight(pTagObjs, false);
	}
	return tagFace;
}

void print0(const char* szFormat, ...)
{
	char szMsg[5000] = "";
	va_list arg_ptr;

	va_start(arg_ptr, szFormat);
	vsprintf_s(szMsg, szFormat, arg_ptr);
	va_end(arg_ptr);
	UF_UI_open_listing_window();
	UF_UI_write_listing_window(szMsg);
	return;
}

//测量面积
double GetFaceArea(tag_t face)
{
	// 抽取片体
	tag_t solid = NULL_TAG;
	UF_MODL_extract_face(face, 0, &solid);

	// 测量片体面积
	int units = UF_MODL_grams_centimeters; //克和厘米
	double acc[11] = { 0.99, 0,0,0,0,0,0,0,0,0,0 };
	double mass_props[47] = { 0 };
	double stats[13] = { 0 };
	UF_MODL_ask_mass_props_3d(&solid, 1, 2, units, 1, 1, acc, mass_props, stats);

	// 删除片体
	//UF_OBJ_delete_object(solid);
	return mass_props[0] * 100; //转为平方毫米
}


void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	tag_t face = SelectFace0();
	double area = GetFaceArea(face);
	print0("area : %f mm2", area);

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

