### UGNX二次开发 代工分享的“单个体XY排料工具”源码

#### 代码

```cpp
//单个体XY排料 代工QQ:873058673
//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int daigong_PL::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == selection0)
        {
        //---------Enter your code here-----------
        }
        else if(block == string02)
        {
        //---------Enter your code here-----------
        }
        else if(block == string0)
        {
        //---------Enter your code here-----------
        }
        else if(block == string03)
        {
        //---------Enter your code here-----------
        }
        else if(block == string01)
        {
        //---------Enter your code here-----------
        }
        else if(block == button0)
        {
			string02->GetProperties()->SetString("Value", "");//设置字符串内容
			string03->GetProperties()->SetString("Value", "");//设置字符串内容
			string01->GetProperties()->SetString("Value", "");//设置字符串内容
			string0->GetProperties()->SetString("Value", "");//设置字符串内容
        }
        else if(block == button01)
        {
			vector<TaggedObject*> selObjs = selection0->GetProperties()->GetTaggedObjectVector("SelectedObjects");//获取对象
	        string strValue = string02->Value().GetLocaleText();//这也可以直接获取 
	        string strValue1 = string03->Value().GetLocaleText();//这也可以直接获取 
			string strValue2 = string0->Value().GetLocaleText();//这也可以直接获取 
			string strValue3 = string01->Value().GetLocaleText();//这也可以直接获取 
			if (strValue == "") { strValue = "0"; }
			if (strValue1 == "") { strValue1 = "0"; }
			if (strValue2 == "") { strValue2 = "0"; }
			if (strValue3 == "") { strValue3 = "0"; }
	  double x1 = 代::str_double(strValue);
	  int x11 = 代::str_int(strValue1);
	  double y1 = 代::str_double(strValue2);
	  int y11 = 代::str_int(strValue3);
			tag_t aa[100];
			if (selObjs[0]->Tag()!=NULL_TAG)

			{
				double minPos[3], maxPos[3];
				for (int i = 0; i<selObjs.size(); i++)
				{
					aa[i] = selObjs[i]->Tag();
					UF_DISP_set_highlight(selObjs[i]->Tag(), 0);
					//UF_MODL_put_list_item(pFeatureList, selObjs[i]->Tag());
					double min_corner[3], max_corner[3];
					double directions[3][3];
					double distances[3];
					UF_MODL_ask_bounding_box_exact(selObjs[i]->Tag(), NULL_TAG, min_corner, directions, distances);
					//min_corner[3], 返回一个面的最小点坐标。distances [ 3 ];返回参考wcs方向的长宽高数
					max_corner[0] = min_corner[0] + distances[0];
					max_corner[1] = min_corner[1] + distances[1];
					max_corner[2] = min_corner[2] + distances[2];//最小点坐标加上长宽高就等于最大点坐标 
					if (i == 0)
					{
						minPos[0] = min_corner[0];//如果我们只选了一个面就把最大点和最小点的坐标传出去
						minPos[1] = min_corner[1];
						minPos[2] = min_corner[2];
						maxPos[0] = max_corner[0];
						maxPos[1] = max_corner[1];
						maxPos[2] = max_corner[2];
					}
					else
					{
						if (min_corner[0]<minPos[0])  minPos[0] = min_corner[0];
						if (min_corner[1]<minPos[1])  minPos[1] = min_corner[1];
						if (min_corner[2]<minPos[2])  minPos[2] = min_corner[2];

						if (max_corner[0]>maxPos[0])  maxPos[0] = max_corner[0];
						if (max_corner[1]>maxPos[1])  maxPos[1] = max_corner[1];
						if (max_corner[2]>maxPos[2])  maxPos[2] = max_corner[2];//没获得一个面判断他的最小点坐标和最大点坐标求出所选的所有面的最小点坐标和最大点坐标< /FONT>
					}
				}


				double boxLenght[3];
				boxLenght[0] = maxPos[0] - minPos[0];
				boxLenght[1] = maxPos[1] - minPos[1];
				boxLenght[2] = maxPos[2] - minPos[2];//最大点坐标减去最小点坐标 就等于长宽高的数

			//	char strC[256], strK[256], strG[256];
			//	sprintf(strC, "%f", boxLenght[0]);
				//sprintf(strK, "%f", boxLenght[1]);
				//sprintf(strG, "%f", boxLenght[2]);
				
			
				if(x11>0){
					for (int s = 0; s < x11;s++) {

					//沿着X轴方向移动 20
					double dDir[3] = { (boxLenght[0]+x1)*(s+1),0.0,0.0 };
					double dMatrix[12] = { 0.0 };
					//获取变换矩阵
					uf5943(dDir, dMatrix);

					int count = selObjs.size();
					int move_or_copy = 2;//1 Move  2 copy
					int dest_layer = 0;
					int trace_curves = 2;//轨迹曲线状态1 on, 2 off.
					tag_t tagCopyObj = NULL;
					tag_t trace_curve_group = NULL;
					int status_value = 0;
					//执行变换
					uf5947(dMatrix, aa, &count, &move_or_copy, &dest_layer,
						&trace_curves, &tagCopyObj, &trace_curve_group, &status_value);
				

				}
				
				}
			   if (y11>0) {
					for (int s = 0; s < y11; s++) {

						//沿着X轴方向移动 20
						double dDir[3] = { 0.0 ,(boxLenght[1] + y1)*(s + 1),0.0 };
						double dMatrix[12] = { 0.0 };
						//获取变换矩阵
						uf5943(dDir, dMatrix);

						int count = selObjs.size();
						int move_or_copy = 2;//1 Move  2 copy
						int dest_layer = 0;
						int trace_curves = 2;//轨迹曲线状态1 on, 2 off.
						tag_t tagCopyObj = NULL;
						tag_t trace_curve_group = NULL;
						int status_value = 0;
						//执行变换
						uf5947(dMatrix, aa, &count, &move_or_copy, &dest_layer,
							&trace_curves, &tagCopyObj, &trace_curve_group, &status_value);


					}

				}

			   if (x11>0 && y11>0) {
				   for (int s = 1; s < y11+1; s++) {
					   for(int t=1;t<x11+1;t++){
					   //沿着X轴方向移动 20
					   double dDir[3] = { (boxLenght[0] + x1)*t ,(boxLenght[1] + y1)*(s),0.0 };
					   double dMatrix[12] = { 0.0 };
					   //获取变换矩阵
					   uf5943(dDir, dMatrix);

					   int count = selObjs.size();
					   int move_or_copy = 2;//1 Move  2 copy
					   int dest_layer = 0;
					   int trace_curves = 2;//轨迹曲线状态1 on, 2 off.
					   tag_t tagCopyObj = NULL;
					   tag_t trace_curve_group = NULL;
					   int status_value = 0;
					   //执行变换
					   uf5947(dMatrix, aa, &count, &move_or_copy, &dest_layer,
						   &trace_curves, &tagCopyObj, &trace_curve_group, &status_value);

}
				   }
			   }
			


			}
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        daigong_PL::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}
```

#### 代码解析
> 未找到解析内容

