### UGNX二次开发 获取曲面uv中心点 UF_MODL_ask_face_props

#### 代码

```cpp
#include "me.hpp"

void AskFaceMidpoint()
{
	//选择面
	tag_t face = selectFace();

	//计算uv参数的最小值最大值
	double uvMinMax[4];
	UF_MODL_ask_face_uv_minmax(face, uvMinMax);//uf5404 也可以

	//输入参数（param[2]）必须在面的Umin、Umax、Vmin和Vmax之间，我们取uv中间就是面中心。
	double param[2] = { 0 };
	param[0] = (uvMinMax[0] + uvMinMax[1]) / 2.0;
	param[1] = (uvMinMax[2] + uvMinMax[3]) / 2.0;

	double point[3] = { 0 };
	double u1[3] = { 0 };
	double v1[3] = { 0 };
	double u2[3] = { 0 };
	double v2[3] = { 0 };
	double unit_norm[3] = { 0 };
	double radii[2] = { 0 };
	UF_MODL_ask_face_props(face, param, point, u1, v1, u2, v2, unit_norm, radii);
	tag_t facePoint;
	UF_CURVE_create_point(point, &facePoint);



}
void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();
	AskFaceMidpoint();
	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

