### UGNX二次开发 获取曲面上指定位置的面方向 UF_MODL_ask_face_props

#### 代码

```cpp
#include "me.hpp"
static void AskFaceDir(tag_t face_id, double* ref_pnt, double* dir)
{
	double
		parm[2],
		pnt[3],
		dirU2[3],
		dirV1[3],
		dirV2[3],
		radii[2],
		x_dir[3];

	UF_MODL_ask_face_parm(face_id, ref_pnt, parm, pnt);
	UF_MODL_ask_face_props(face_id, parm, pnt, x_dir, dirV1, dirU2,
		dirV2, dir, radii);

	//UF_VEC3_negate(dir, dir); //反向
	DisplayConehead(pnt, dir);
}

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	//选择面
	tag_t face = selectFace();
	//选择点
	double refPoint[3] = { 0 };
	SelectPoint(refPoint);

	double faceDir[3] = { 0 };
	AskFaceDir(face, refPoint, faceDir);
	

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}
```

#### 代码解析
> 未找到解析内容

