### UGNX二次开发 获取曲面上指定点位置的uv参数 UF_MODL_ask_face_parm

#### 代码

```cpp
#include "me.hpp"

//parm[2]
static void AskFaceUVParm(tag_t face_id, double* ref_pnt, double* parm)
{
	double
		pnt[3],
		dirU2[3],
		dirV1[3],
		dirV2[3],
		radii[2],
		x_dir[3];

	UF_MODL_ask_face_parm(face_id, ref_pnt, parm, pnt);
}

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	//选择面
	tag_t face = selectFace();
	//选择点
	double refPoint[3] = { 0 };
	SelectPoint(refPoint);

	double parm[2] = { 0 };
	AskFaceUVParm(face, refPoint, parm);
	print("U parm = %f\n", parm[0]);
	print("V parm = %f\n", parm[0]);
	

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

