### UGNX二次开发 判断是不是圆平面

#### 代码

```cpp
#include "me.hpp"

//获取面的所有边
vector<tag_t> GetFaceEdges(tag_t face)
{
	vector<tag_t> edges;
	uf_list_p_t list1 = NULL;
	UF_MODL_create_list(&list1);
	UF_MODL_ask_face_edges(face, &list1);
	int count = 0;
	UF_MODL_ask_list_count(list1, &count);
	for (int i = 0; i < count; i++)
	{
		tag_t tagEdge = NULL_TAG;
		UF_MODL_ask_list_item(list1, i, &tagEdge);
		edges.push_back(tagEdge);
	}
	UF_free(list1);
	list1 = NULL;
	return edges;
}


//判断面是不是圆平面
bool IsCircularPlane(tag_t face)
{
	vector<tag_t>edges = GetFaceEdges(face);
	if (edges.size() == 1)
	{
		int edgeType = 0;
		UF_MODL_ask_edge_type(edges[0], &edgeType);
		if (edgeType == UF_MODL_CIRCULAR_EDGE)
		{
			return true;
		}
	}
	return false;
}



extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();

	tag_t face = selectFace();
	if (IsCircularPlane(face))
	{
		uc1601("是圆平面", 1);
	}
	else
	{
		uc1601("不是圆平面", 1);
	}
	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

