### UGNX二次开发 获取面上随机一条圆弧边的直径

#### 代码

```cpp
#include "me.hpp"

//随机获取一条圆弧边的直径，没有圆弧边返回0.0
double GetFaceEdgeDia(tag_t face)
{
	tag_t edge = NULL_TAG;
	uf_list_p_t list1 = NULL;
	UF_MODL_create_list(&list1);
	UF_MODL_ask_face_edges(face, &list1);
	int count = 0;
	UF_MODL_ask_list_count(list1, &count);
	for (int i = 0; i < count; i++)
	{
		tag_t itm = NULL_TAG;
		UF_MODL_ask_list_item(list1, i, &itm);
		int edgeType = 0;
		UF_MODL_ask_edge_type(itm, &edgeType);
		if (edgeType == UF_MODL_CIRCULAR_EDGE)
		{
			edge = itm;
			break;
		} 
	}
	UF_free(list1);
	list1 = NULL;

	double dia = 0.0;
	if (edge != NULL_TAG)
	{
		UF_CURVE_arc_t    arcCoords;
		UF_CURVE_ask_arc_data(edge, &arcCoords);
		dia = arcCoords.radius * 2.0;
	}
	return dia;
}

extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();
	
	tag_t face = selectFace();
	double dia = GetFaceEdgeDia(face);
	print("直径dia=%f\n", dia);

	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

