### UGNX二次开发 获取圆柱面的长度

#### 代码

```cpp
#include "me.hpp"

double GetCylinderLength_lhi(tag_t cylinderFace)
{
	//获取面方向
	int type = 0;
	int norm_dir = 0;
	double point[3];
	double dir[3];
	double box1[6];
	double radius;
	double rad_data;
	UF_MODL_ask_face_data(cylinderFace, &type, point, dir, box1, &radius, &rad_data, &norm_dir);

	//获取矩阵
	double mtxValue[9] = { 0.0 };
	UF_MTX3_initialize_z(dir, mtxValue);
	tag_t mtx = NULL_TAG;
	UF_CSYS_create_matrix(mtxValue, &mtx);

	//创建临时坐标系
	double origin[3] = { 0.0 };
	tag_t tempCsys = NULL_TAG;
	UF_CSYS_create_temp_csys(origin, mtx, &tempCsys);

	//包容盒
	double minCorner[3] = { 0.0 };
	double directions[3][3] = { 0.0 };
	double distances[3] = { 0.0 };
	UF_MODL_ask_bounding_box_exact(cylinderFace, tempCsys, minCorner, directions, distances);

	return distances[2];
}

extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();

	tag_t cylinderFace = selectFace();
	double len = GetCylinderLength_lhi(cylinderFace);
	print(len);

	
	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

```cpp
void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	tag_t face = SelectFace();

	auto start = std::chrono::high_resolution_clock::now();
	for (int i = 0; i < 100000; i++)
		GetCylinderLength_lhi(face);

	auto end = std::chrono::high_resolution_clock::now();
	auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
	print("%d 毫秒\n", duration);

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

