### 获取片体的边界UF_MODL_ask_body_boundaries()

#### 代码

```cpp
#include "me.hpp"
#include <uf.h>
#include <uf_modl.h>
#include <uf_disp.h>
//获取片体的边界
void GetSheetBodyBoundariesLh(tag_t body)
{
    //边界数量
    int iBoundariesCount = 0;
    int* iEdgesCount;
    tag_t* tagEdges;
    int iEdgeSumCount = 0;
    UF_MODL_ask_body_boundaries(body, &iBoundariesCount, &iEdgesCount, &tagEdges);

    print("边界数量%d\n", iBoundariesCount);
    for (int i = 0; i < iBoundariesCount; i++)
    {
        print("第%d个边界的边数量：%d\n",i+1, iEdgesCount[i]);
    }

    //设置第二个边界高亮
    if (iBoundariesCount >= 2)
    {
        //第二个边界的边数量
        int c2 = iEdgesCount[1];
        //第二个边界的边指针
        tag_t *e2 = tagEdges + iEdgesCount[0];//指针偏移

        for (int i = 0; i < c2; i++)
        {
            UF_DISP_set_highlight(e2[i], TRUE);//TRUE高亮显示  FALSE取消高亮显示
        }
    }
    UF_free(iEdgesCount);
    UF_free(tagEdges);
}
  
extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();

    tag_t body = selectBody();
    GetSheetBodyBoundariesLh(body);
	
	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

