### UG、NX二次开发 获取边对应的面 UF_MODL_ask_edge_faces

#### 代码

```cpp
#include "me.hpp"

std::vector<tag_t> GetEdgeFaceLH(tag_t edge, int faceType)
{
	uf_list_p_t listFace = NULL;
	UF_MODL_create_list(&listFace);
	UF_MODL_ask_edge_faces(edge, &listFace);
	std::vector<tag_t> faces;
	for (uf_list_p_t temp = listFace; temp != NULL; temp = temp->next)
	{
		int type = 0;
		UF_MODL_ask_face_type(temp->eid, &type);
		if (faceType == 0 || faceType == type)
			faces.push_back(temp->eid);
	}
	UF_free(listFace);
	listFace = NULL;
	return faces;
}

extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();

	tag_t edge = selectEdge();
	std::vector<tag_t> edgeFaces = GetEdgeFaceLH(edge, 0);
	SetObjHighlight(edgeFaces);

	UF_terminate();
}

```

#### 代码解析
> 未找到解析内容

