### UGNX二次开发 在wcs原点位置生成文本曲线特征 FeaturesTextBuilder

#### 代码

```cpp
#include "me.hpp"

//文本曲线的头文件
#include <uf_defs.h>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/CoordinateSystem.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/ExpressionCollection.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/Features_TextBuilder.hxx>
#include <NXOpen/Features_ToolingBox.hxx>
#include <NXOpen/GeometricUtilities_FrameOnPathBuilder.hxx>
#include <NXOpen/GeometricUtilities_OnPathDimensionBuilder.hxx>
#include <NXOpen/GeometricUtilities_RectangularFrameBuilder.hxx>
#include <NXOpen/ModelingView.hxx>
#include <NXOpen/ModelingViewCollection.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Plane.hxx>
#include <NXOpen/PlaneCollection.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/PointCollection.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Scalar.hxx>
#include <NXOpen/ScalarCollection.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectSmartObject.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/SmartObject.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/Unit.hxx>
#include <NXOpen/Xform.hxx>
#include <NXOpen/XformCollection.hxx>
//-----------
using namespace std;
using namespace LiHai;
using namespace NXOpen;

/// <summary>
/// 在wcs原点位置生成文本
/// </summary>
/// <param name="textStr">文本内容</param>
/// <param name="font">文本字体</param>
/// <param name="height">文本高度</param>
/// <param name="width">文本宽度</param>
tag_t Text(string textStr, string font, double height, double width);

extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();

	tag_t textFeat = Text("是里海啊", "Arial", 10, 100);
	
	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


tag_t Text(string textStr,string font,double height,double width)
{
	Session* theSession = Session::GetSession();
	Part* workPart(theSession->Parts()->Work());
	Part* displayPart(theSession->Parts()->Display());
	Features::Text* nullFeatures_Text(NULL);
	Features::TextBuilder* textBuilder1;
	textBuilder1 = workPart->Features()->CreateTextBuilder(nullFeatures_Text);
	textBuilder1->FrameOnPath()->AnchorPosition()->Expression()->SetRightHandSide("51");
	//设置文本锚点位置为底部中心
	textBuilder1->PlanarFrame()->SetAnchorLocation(GeometricUtilities::RectangularFrameBuilder::AnchorLocationTypeBottomCenter);
	//设置文本高度
	textBuilder1->PlanarFrame()->Height()->SetRightHandSide(to_string(height).c_str());
	//设置文本宽度
	textBuilder1->PlanarFrame()->SetWScale(width);
	//设置文本字体
	textBuilder1->SelectFont(NXString(font.c_str()), Features::TextBuilder::ScriptOptionsWestern);
	//设置文本内容
	textBuilder1->SetTextString(NXString(textStr.c_str()));
	//设置锚点位置 在wcs原点下二分之一字体高度位置
	double pickPointClick[3] = { 0, -height / 2,0 };
	UF_CSYS_map_point(UF_CSYS_ROOT_WCS_COORDS, pickPointClick, UF_CSYS_ROOT_COORDS, pickPointClick);
	Point3d pickPointClick0 = { pickPointClick[0],pickPointClick[1],pickPointClick[2] };
	Point* point2 = workPart->Points()->CreatePoint(pickPointClick0);
	textBuilder1->PlanarFrame()->AnchorLocator()->SetValue(point2, displayPart->ModelingViews()->WorkView(), pickPointClick0);
	textBuilder1->PlanarFrame()->UpdateOnCoordinateSystem();
	NXObject* textFeat = textBuilder1->Commit();
	textBuilder1->Destroy();
	return textFeat->Tag();
}

```

#### 代码解析
> 未找到解析内容

