### UGNX二次开发 使用文本特征创建拉伸特征 FeaturesExtrudeBuilder

#### 代码

```cpp
#include "me.hpp"

//拉伸的头文件
#include <uf_defs.h>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/CurveFeatureRule.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/ExpressionCollection.hxx>
#include <NXOpen/Features_ExtrudeBuilder.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/Features_Text.hxx>
#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
#include <NXOpen/GeometricUtilities_Extend.hxx>
#include <NXOpen/GeometricUtilities_FeatureOffset.hxx>
#include <NXOpen/GeometricUtilities_FeatureOptions.hxx>
#include <NXOpen/GeometricUtilities_Limits.hxx>
#include <NXOpen/GeometricUtilities_MultiDraft.hxx>
#include <NXOpen/GeometricUtilities_SimpleDraft.hxx>
#include <NXOpen/GeometricUtilities_SmartVolumeProfileBuilder.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SectionCollection.hxx>
#include <NXOpen/SelectionIntentRule.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/SmartObject.hxx>
#include <NXOpen/Unit.hxx>
#include <NXOpen/Spline.hxx>
//-----------
using namespace std;
using namespace LiHai;
using namespace NXOpen;


/// <summary>
/// 使用文本特征创建拉伸特征
/// </summary>
/// <param name="textFeat">文本特征</param>
/// <param name="dir">拉伸方向</param>
/// <param name="startExtend">拉伸开始值</param>
/// <param name="endExtend">拉伸结束值</param>
/// <returns>拉伸特征</returns>
tag_t Extrude(tag_t textFeat, double dir[3], string startExtend, string endExtend);

extern DllExport void ufusr(char* param, int* returnCode, int rlen)
{
	UF_initialize();

	//拉伸的文本特征
	tag_t textFeat = SelectFeat();
	//拉伸方向
	double dir[3] = { 0.0,0.0,1.0 };
	//拉伸开始、结束值
	string startExtend = "-1";
	string endExtend = "2";
	tag_t ex = Extrude(textFeat, dir, startExtend, endExtend);

	UF_terminate();
}

extern int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

tag_t Extrude(tag_t textFeat, double dir[3], string startExtend, string endExtend) 
{
	Session* theSession = Session::GetSession();
	Part* workPart(theSession->Parts()->Work());
	Part* displayPart(theSession->Parts()->Display());

	Features::Feature* nullFeatures_Feature1(NULL);
	Features::ExtrudeBuilder* extrudeBuilder1;
	extrudeBuilder1 = workPart->Features()->CreateExtrudeBuilder(nullFeatures_Feature1);

	Section* section1;
	section1 = workPart->Sections()->CreateSection(0.0, 0.0,0.0);

	extrudeBuilder1->SetSection(section1);

	extrudeBuilder1->SetDistanceTolerance(0.001);
	extrudeBuilder1->BooleanOperation()->SetType(GeometricUtilities::BooleanOperation::BooleanTypeCreate);    //creat
	std::vector<Body*> targetBodies1(1);
	Body* nullBody(NULL);
	targetBodies1[0] = nullBody;
	extrudeBuilder1->BooleanOperation()->SetTargetBodies(targetBodies1);
	extrudeBuilder1->BooleanOperation()->SetType(GeometricUtilities::BooleanOperation::BooleanTypeCreate);
	std::vector<Body*> targetBodies2(1);
	targetBodies2[0] = nullBody;
	extrudeBuilder1->BooleanOperation()->SetTargetBodies(targetBodies2);
	GeometricUtilities::SmartVolumeProfileBuilder* smartVolumeProfileBuilder1;
	smartVolumeProfileBuilder1 = extrudeBuilder1->SmartVolumeProfile();
	smartVolumeProfileBuilder1->SetOpenProfileSmartVolumeOption(false);
	smartVolumeProfileBuilder1->SetCloseProfileRule(GeometricUtilities::SmartVolumeProfileBuilder::CloseProfileRuleTypeFci);
	section1->SetDistanceTolerance(0.001);
	section1->SetChainingTolerance(0.00095);
	section1->SetAllowedEntityTypes(Section::AllowTypesOnlyCurves);
	
	std::vector<Features::Feature*> features1(1);
	Features::Text* text1(dynamic_cast<Features::Text*>(NXOpen::NXObjectManager::Get(textFeat)));
	features1[0] = text1;
	CurveFeatureRule* curveFeatureRule1;
	curveFeatureRule1 = workPart->ScRuleFactory()->CreateRuleCurveFeature(features1);
	section1->AllowSelfIntersection(true);
	std::vector<SelectionIntentRule*> rules1(1);
	rules1[0] = curveFeatureRule1;
	Spline* spline1(dynamic_cast<Spline*>(text1->FindObject("CURVE 1 {9 (-23.3249439696624,5.4392703236035,0)}")));
	NXObject* nullNXObject(NULL);
	Point3d helpPoint1(-22.0151460673856, 2.40290725417247, 0.0);
	section1->AddToSection(rules1, spline1, nullNXObject, nullNXObject, helpPoint1, Section::ModeCreate, false);

	Point3d origin2(0.0,0.0, 0.0);
	Vector3d vector1(dir[0], dir[1], dir[2]);
	Direction* direction1;
	direction1 = workPart->Directions()->CreateDirection(origin2, vector1, SmartObject::UpdateOptionWithinModeling);
	extrudeBuilder1->SetDirection(direction1);

	extrudeBuilder1->Limits()->StartExtend()->Value()->SetRightHandSide(startExtend.c_str());
	extrudeBuilder1->Limits()->EndExtend()->Value()->SetRightHandSide(endExtend.c_str());
	extrudeBuilder1->SetParentFeatureInternal(false);

	Features::Feature* feature1;
	feature1 = extrudeBuilder1->CommitFeature();

	extrudeBuilder1->Destroy();

	return feature1->Tag();

}

```

#### 代码解析
> 未找到解析内容

