### UGNX二次开发 获取圆锥面的最大直径边的直径

#### 代码

```cpp
#include "me.hpp"
using namespace std;
using namespace LiHai;

std::vector<tag_t> GetFaceEdges0(tag_t face, int edgeType)
{
	// UF_MODL_LINEAR_EDGE 直线边
	// UF_MODL_CIRCULAR_EDGE 圆边
	// UF_MODL_ELLIPTICAL_EDGE 椭圆边
	// UF_MODL_INTERSECTION_EDGE 交线边
	// UF_MODL_SPLINE_EDGE 样条边
	// UF_MODL_SP_CURVE_EDGE sp曲线边
	// UF_MODL_FOREIGN_EDGE 外来边边
	// UF_MODL_CONST_PARAMETER_EDGE 等参曲线边
	// UF_MODL_TRIMMED_CURVE_EDGE 修整曲线边
	uf_list_p_t listEdge = NULL;
	UF_MODL_create_list(&listEdge);
	UF_MODL_ask_face_edges(face, &listEdge);
	std::vector<tag_t> edges;
	int count = 0;
	UF_MODL_ask_list_count(listEdge, &count);
	for (int i = 0; i < count; i++)
	{
		tag_t edge = NULL_TAG;
		UF_MODL_ask_list_item(listEdge, i, &edge);

		int type = 0;
		UF_MODL_ask_edge_type(edge, &type);

		if (edgeType == 0 || edgeType == type)
			edges.push_back(edge);
	}
	UF_free(listEdge);
	listEdge = NULL;
	return edges;
}

double GetArcRadius0(tag_t arc)
{
	double rValue = 0.0;
	UF_EVAL_p_t evaluator = NULL;
	UF_EVAL_initialize(arc, &evaluator);
	logical is_arc = false;
	UF_EVAL_is_arc(evaluator, &is_arc);
	if (is_arc)
	{
		UF_EVAL_arc_t arcEval;
		UF_EVAL_ask_arc(evaluator, &arcEval);
		rValue = arcEval.radius;
	}
	UF_EVAL_free(evaluator);

	return rValue;
}

// 返回圆锥面底圆弧边直径
double GetMaxDiameterOfCone0(tag_t face)
{
	// 1. 圆弧
	// 2. 直径最大
	std::vector<tag_t> edges = GetFaceEdges0(face, UF_MODL_CIRCULAR_EDGE);
	double dia = 0.0;
	for (auto edge : edges)
	{
		double rad = GetArcRadius0(edge);
		if (rad * 2.0 > dia)
			dia = rad * 2.0;
	}
	return dia;
}

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	tag_t selFace = LiHai::SelectFace();

	int faceType = 0;
    UF_MODL_ask_face_type(selFace, &faceType);

    if (faceType == UF_MODL_CONICAL_FACE) //如果是圆锥面
    {
		double dia = GetMaxDiameterOfCone0(selFace);
		print(dia);

	}
	
	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

#### 代码解析
> 未找到解析内容

