### UGNX二次开发 获取圆弧、椭圆所在平面的方向

#### 代码

```cpp
std::array<double, 3> GetArcDir0(tag_t tagArc)
{
	int edge_type = 0;
	UF_MODL_ask_edge_type(tagArc, &edge_type);
	if (edge_type == UF_MODL_CIRCULAR_EDGE)
	{
		UF_EVAL_p_t evaluator;
		UF_EVAL_initialize(tagArc, &evaluator);
		UF_EVAL_arc_s  arc;
		UF_EVAL_ask_arc(evaluator, &arc);

		double zAxis[3] = { 0.0 };
		UF_VEC3_cross(arc.x_axis, arc.y_axis, zAxis);

		UF_EVAL_free(evaluator);

		return { zAxis[0],zAxis[1],zAxis[2] };
	}
	else if (edge_type == UF_MODL_ELLIPTICAL_EDGE)	// 椭圆
	{
		UF_EVAL_p_t evaluator;
		UF_EVAL_initialize(tagArc, &evaluator);
		UF_EVAL_ellipse_s arc;
		UF_EVAL_ask_ellipse(evaluator, &arc);

		double zAxis[3] = { 0.0 };
		UF_VEC3_cross(arc.x_axis, arc.y_axis, zAxis);

		UF_EVAL_free(evaluator);

		return { zAxis[0],zAxis[1],zAxis[2] };
	}
	else
	{

	}
	return { 0.0,0.0,0.0 };
}

```

#### 代码解析
> 未找到解析内容

