### UGNX二次开发 使用获取圆弧、椭圆的直径UF_EVAL_ask_ellipse

#### 代码

```cpp
std::array<double, 3> LiHai::GetArcCenter(tag_t tagArc)
{
	std::array<double, 3> center;
	int edge_type = 0;
	UF_MODL_ask_edge_type(tagArc, &edge_type);
	if (edge_type == UF_MODL_CIRCULAR_EDGE)
	{
		UF_EVAL_p_t evaluator;
		UF_EVAL_initialize(tagArc, &evaluator);
		UF_EVAL_arc_s  arc;
		UF_EVAL_ask_arc(evaluator, &arc);
		center[0] = arc.center[0];
		center[1] = arc.center[1];
		center[2] = arc.center[2];
		UF_EVAL_free(evaluator);
	}
	else if (edge_type == UF_MODL_ELLIPTICAL_EDGE)	// 椭圆
	{
		UF_EVAL_p_t evaluator;
		UF_EVAL_initialize(tagArc, &evaluator);
		UF_EVAL_ellipse_s arc;
		UF_EVAL_ask_ellipse(evaluator, &arc);
		center[0] = arc.center[0];
		center[1] = arc.center[1];
		center[2] = arc.center[2];
		UF_EVAL_free(evaluator);
	}
	else
	{
		
	}
	return center;
}

```

#### 代码解析
> 未找到解析内容

