### UGNX二次开发 获取面的圆锥类型相邻面

#### 代码

```cpp
#include "me.hpp"
using namespace std;

std::vector<tag_t> GetAdjacentFaces0(tag_t face)
{
	uf_list_p_t listFace = NULL;
	UF_MODL_create_list(&listFace);
	UF_MODL_ask_adjac_faces(face, &listFace);
	std::vector<tag_t> faces;
	for (uf_list_p_t temp = listFace; temp != NULL; temp = temp->next)
	{
		faces.push_back(temp->eid);
	}
	UF_MODL_delete_list(&listFace);
	return faces;
}

tag_t GetConFace(tag_t cylFace)
{
	vector<tag_t>  adjFaces = GetAdjacentFaces0(cylFace);
	for (auto fa : adjFaces)
	{
		int faceType;
		UF_MODL_ask_face_type(fa, &faceType);
		if (faceType == UF_MODL_CONICAL_FACE)
			return fa;
	}
	return null_tag;
}

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	tag_t cylFace = SelectFace();
	tag_t cFace =  GetConFace(cylFace);
	if(cFace != null_tag)
		UF_DISP_set_highlight(cFace, 1);
	
	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

```cpp
//获取面的圆锥类型相邻面
tag_t GetConFace(tag_t cylFace)
{
	uf_list_p_t listFace = NULL;
	UF_MODL_create_list(&listFace);
	UF_MODL_ask_adjac_faces(cylFace, &listFace);
	std::vector<tag_t> faces;
	for (uf_list_p_t temp = listFace; temp != NULL; temp = temp->next)
	{
		faces.push_back(temp->eid);
	}
	UF_MODL_delete_list(&listFace);

	for (auto fa : faces)
	{
		int faceType;
		UF_MODL_ask_face_type(fa, &faceType);
		if (faceType == UF_MODL_CONICAL_FACE)
			return fa;
	}
	return null_tag;
}

```

#### 代码解析
> 未找到解析内容

