### UGNX二次开发 查询面的拓扑结构

#### 代码

```cpp
#include "me.hpp"
using namespace std;
using namespace LiHai;

void AskFaceTopology_LH(tag_t face)
{
	int topoType = 0;
	UF_MODL_ask_face_topology(face, &topoType);

	if (topoType == UF_MODL_FLAT_TOPOLOGY)
	{
		print("UF_MODL_FLAT_TOPOLOGY ");
		print("面有一个外围边缘环\n");
	}
	else if (topoType == UF_MODL_CYLINDRICAL_TOPOLOGY)
	{
		print("UF_MODL_CYLINDRICAL_TOPOLOGY ");
		print("面有两个外围边缘环，但没有极点\n");
	}
	else if (topoType == UF_MODL_CONICAL_TOPOLOGY)
	{
		print("UF_MODL_CONICAL_TOPOLOGY ");
		print("面有两个外围边缘环和一个极点\n");
	}
	else if (topoType == UF_MODL_SPHERICAL_TOPOLOGY)
	{
		print("UF_MODL_SPHERICAL_TOPOLOGY ");
		print("面有两个外围边缘环和两个极点\n");
	}
	else if (topoType == UF_MODL_TOROIDAL_TOPOLOGY)
	{
		print("UF_MODL_TOROIDAL_TOPOLOGY ");
		print("面没有外围边缘环\n");
	}
	else if (topoType == 0)
	{
		print("0");
		print("面是一个具有多个面的体，或者出现错误\n");
	}

	return;
}
void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	tag_t face = SelectFace();
	AskFaceTopology_LH(face);
	
	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

#### 代码解析
> 未找到解析内容

