### UGNX二次开发 获取多个圆柱面的总高度

#### 代码

```cpp
double LiHai::GetCylinderFaceLength(vector<tag_t> cylinderFaces)
{
	if (cylinderFaces.empty()) 
		return 0.0;

	//获取面方向
	int type = 0;
	int norm_dir = 0;
	double point[3];
	double dir[3];
	double box1[6];
	double radius;
	double rad_data;
	UF_MODL_ask_face_data(cylinderFaces[0], &type, point, dir, box1, &radius, &rad_data, &norm_dir);

	//获取矩阵
	double mtxValue[9] = { 0.0 };
	UF_MTX3_initialize_z(dir, mtxValue);
	tag_t mtx = NULL_TAG;
	UF_CSYS_create_matrix(mtxValue, &mtx);

	//创建临时坐标系
	double origin[3] = { 0.0 };
	tag_t tempCsys = NULL_TAG;
	UF_CSYS_create_temp_csys(origin, mtx, &tempCsys);

	UF_CSYS_set_wcs(tempCsys);

	std::array<double, 3> cornerMin;
	std::array<double, 3> cornerMax;
	for (auto face : cylinderFaces)
	{
		std::array<double, 3> cornerMinTemp;
		double directions[3][3] = { 0.0 };
		double distances[3] = { 0.0 };
		UF_MODL_ask_bounding_box_exact(face, tempCsys, cornerMinTemp.data(), directions, distances);
		//LiHai::DisplayTempBox(cornerMinTemp.data(), directions, distances);

		std::array<double, 3> cornerMaxTemp;
		cornerMaxTemp = LiHai::GetMaxCorner(cornerMinTemp, directions, distances);

		cornerMinTemp = LiHai::GetPointAbsToCsys(cornerMinTemp.data(), origin, mtxValue, &mtxValue[3]);
		cornerMaxTemp = LiHai::GetPointAbsToCsys(cornerMaxTemp.data(), origin, mtxValue, &mtxValue[3]);

		if (face == cylinderFaces[0])
		{
			cornerMin = cornerMinTemp;
			cornerMax = cornerMaxTemp;
		}
		else
		{
			if (cornerMin[0] > cornerMinTemp[0])
				cornerMin[0] = cornerMinTemp[0];
			if (cornerMin[1] > cornerMinTemp[1])
				cornerMin[1] = cornerMinTemp[1];
			if (cornerMin[2] > cornerMinTemp[2])
				cornerMin[2] = cornerMinTemp[2];

			if (cornerMax[0] < cornerMaxTemp[0])
				cornerMax[0] = cornerMaxTemp[0];
			if (cornerMax[1] < cornerMaxTemp[1])
				cornerMax[1] = cornerMaxTemp[1];
			if (cornerMax[2] < cornerMaxTemp[2])
				cornerMax[2] = cornerMaxTemp[2];
		}
	}
	return cornerMax[2] - cornerMin[2];
}

```

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();
	
	vector<tag_t> faces = SelectFaces();
	double len = GetCylinderFaceLength(faces);
	print(len);

	UF_terminate();

}
int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

