### UGNX二次开发 获取圆柱面的两个轴上的端点

#### 代码

```cpp
void LiHai::DisplayTempPoint(double point[])
{
	tag_t view = NULL_TAG;
	UF_OBJ_disp_props_t disp;
	disp.layer = 1;
	disp.color = 1;
	disp.blank_status = UF_OBJ_NOT_BLANKED;
	disp.line_width = UF_OBJ_WIDTH_NORMAL;
	disp.font = 5;
	disp.highlight_status = false;
	UF_DISP_poly_marker_t marker_type = UF_DISP_BIG_ASTERISK;
	UF_DISP_display_temporary_point(view, UF_DISP_USE_WORK_VIEW, point, &disp, marker_type);
}
void LiHai::GetCylinderPoint(tag_t cylinderFace, double point1[], double point2[])
{
	//获取面方向
	int type = 0;
	int norm_dir = 0;
	double point[3];
	double dir[3];
	double box1[6];
	double radius;
	double rad_data;
	UF_MODL_ask_face_data(cylinderFace, &type, point, dir, box1, &radius, &rad_data, &norm_dir);

	//获取矩阵
	double mtxValue[9] = { 0.0 };
	UF_MTX3_initialize_z(dir, mtxValue);
	tag_t mtx = NULL_TAG;
	UF_CSYS_create_matrix(mtxValue, &mtx);

	//创建临时坐标系
	double origin[3] = { 0.0 };
	tag_t tempCsys = NULL_TAG;
	UF_CSYS_create_temp_csys(origin, mtx, &tempCsys);

	double minCorner[3] = { 0.0 };
	double directions[3][3] = { 0.0 };
	double distances[3] = { 0.0 };
	UF_MODL_ask_bounding_box_exact(cylinderFace, tempCsys, minCorner, directions, distances);

	for (int i = 0; i < 3; ++i)
		point1[i] = minCorner[i] + directions[0][i] * distances[0]/2.0 + directions[1][i] * distances[1]/2.0;
	
	for (int i = 0; i < 3; ++i)
		point2[i] = point1[i] + directions[2][i] * distances[2];
	
	DisplayTempPoint(point1);
	DisplayTempPoint(point2);
	return ;
}

```

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;


void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();
	
	tag_t cylindeFace = SelectFace();
	double point1[3], point2[3];
	LiHai::GetCylinderPoint(cylindeFace, point1, point2);

	UF_terminate();

}
int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}



```

#### 代码解析
> 未找到解析内容

