### UGNX二次开发 获取多个同轴的圆柱面的两个轴线上的端点

#### 代码

```cpp
void LiHai::GetCylinderPoint(std::vector<tag_t> cylindeFaces, double point1[], double point2[])
{
	//获取面方向
	int type = 0;
	int norm_dir = 0;
	double point[3];
	double dir[3];
	double box1[6];
	double radius;
	double rad_data;
	UF_MODL_ask_face_data(cylindeFaces[0], &type, point, dir, box1, &radius, &rad_data, &norm_dir);

	//获取矩阵
	double mtxValue[9] = { 0.0 };
	UF_MTX3_initialize_z(dir, mtxValue);
	tag_t mtx = NULL_TAG;
	UF_CSYS_create_matrix(mtxValue, &mtx);

	//创建临时坐标系
	tag_t tempCsys = NULL_TAG;
	UF_CSYS_create_temp_csys(point, mtx, &tempCsys);


	double zMin;
	double zMax;
	for (auto cylinderFace : cylindeFaces)
	{
		std::array<double, 3> cornerMinTemp;
		double directions[3][3] = { 0.0 };
		double distances[3] = { 0.0 };
		UF_MODL_ask_bounding_box_exact(cylinderFace, tempCsys, cornerMinTemp.data(), directions, distances);

		std::array<double, 3> cornerMaxTemp;
		cornerMaxTemp = LiHai::GetMaxCorner(cornerMinTemp, directions, distances);

		cornerMinTemp = LiHai::GetPointAbsToCsys(cornerMinTemp.data(), tempCsys);
		cornerMaxTemp = LiHai::GetPointAbsToCsys(cornerMaxTemp.data(), tempCsys);

		if (cylinderFace == cylindeFaces[0])
		{
			zMin = cornerMinTemp[2];
			zMax = cornerMaxTemp[2];
		}
		else
		{
			if (zMin > cornerMinTemp[2])
				zMin = cornerMinTemp[2];

			if (zMax < cornerMaxTemp[2])
				zMax = cornerMaxTemp[2];
		}
	}

	std::array<double, 3> cornerMin = { 0,0,zMin };
	std::array<double, 3> cornerMax = { 0,0,zMax };

	std::array<double, 3> cornerMinAbs = LiHai::GetPointCsysToAbs(cornerMin.data(), tempCsys);
	std::array<double, 3> cornerMaxAbs = LiHai::GetPointCsysToAbs(cornerMax.data(), tempCsys);
	for (int i = 0; i < 3; ++i)
	{
		point1[i] = cornerMinAbs[i];
		point2[i] = cornerMaxAbs[i];
	}
	return;
}

```

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;


void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();
	
	vector<tag_t> cylindeFaces = SelectFaces();
	double point1[3], point2[3];
	LiHai::GetCylinderPoint(cylindeFaces, point1, point2);
	DisplayTempLine(point1, point2);
	DisplayTempPoint(point1);
	DisplayTempPoint(point2);

	UF_terminate();

}
int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

#### 代码解析
> 未找到解析内容

