### UGNX二次开发 创建一条直线UF_CURVE_create_line

#### 代码

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;

tag_t CreateLine(double startPoint[], double endPoint[])
{
	UF_CURVE_line_t lineData;
	tag_t lineTag;
	for (int i = 0; i < 3; i++)
	{
		lineData.start_point[i] = startPoint[i];
		lineData.end_point[i] = endPoint[i];
	}
	UF_CURVE_create_line(&lineData, &lineTag);
	return lineTag;
}
void ufusr
(char* param, int* retcode, int paramLen)
{
	UF_initialize();
	
	double startPoint[] = { 0,0,1 };
	double endPoint[] = { 0,2.5,0 };
	tag_t lineTag = CreateLine(startPoint, endPoint);

	UF_terminate();

}
int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}



```

#### 代码解析
> 未找到解析内容

