### UGNX二次开发 使用NXOpen封装函数实现创建“移动面”特征 NXOpenFeaturesAdmMoveFaceBuilder

#### 代码

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;

// --------------移动面------------
#include <uf_defs.h>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/Axis.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/CoordinateSystem.hxx>
#include <NXOpen/Curve.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/FaceDumbRule.hxx>
#include <NXOpen/Features_AdmMoveFaceBuilder.hxx>
#include <NXOpen/Features_Brep.hxx>
#include <NXOpen/Features_FaceRecognitionBuilder.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/GeometricUtilities_FaceChangeOverflowBehavior.hxx>
#include <NXOpen/GeometricUtilities_ModlAlongCurveAngle.hxx>
#include <NXOpen/GeometricUtilities_ModlDistanceAngle.hxx>
#include <NXOpen/GeometricUtilities_ModlMotion.hxx>
#include <NXOpen/GeometricUtilities_OnPathDimensionBuilder.hxx>
#include <NXOpen/GeometricUtilities_OrientXpressBuilder.hxx>
#include <NXOpen/GeometricUtilities_StepOptionBehavior.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <NXOpen/SelectCurve.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectionIntentRule.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/SmartObject.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/Unit.hxx>
//---------------------------------

tag_t CreateMoveFaceFeat(vector<tag_t>faces, double dir[], double dis)
{

    NXOpen::Session* theSession = NXOpen::Session::GetSession();
    NXOpen::Part* workPart(theSession->Parts()->Work());
    NXOpen::Part* displayPart(theSession->Parts()->Display());

    NXOpen::Features::AdmMoveFace* nullNXOpen_Features_AdmMoveFace(NULL);
    NXOpen::Features::AdmMoveFaceBuilder* admMoveFaceBuilder1;
    admMoveFaceBuilder1 = workPart->Features()->CreateAdmMoveFaceBuilder(nullNXOpen_Features_AdmMoveFace);

    // 设置移动面的范围关系
    admMoveFaceBuilder1->FaceToMove()->SetRelationScope(511);

    // 设置移动的增量参考为工作部件的ACS
    admMoveFaceBuilder1->Motion()->SetDeltaEnum(NXOpen::GeometricUtilities::ModlMotion::DeltaReferenceAcsWorkPart);

    // 设置移动选项为距离
    admMoveFaceBuilder1->Motion()->SetOption(NXOpen::GeometricUtilities::ModlMotion::OptionsDistance);

    // 定义原点
    NXOpen::Point3d origin1(0.0, 0.0, 0.0);
    // 定义向量
    NXOpen::Vector3d vector1(dir[0], dir[1], dir[2]);
    // 创建方向
    NXOpen::Direction* direction1;
    direction1 = workPart->Directions()->CreateDirection(origin1, vector1, NXOpen::SmartObject::UpdateOptionWithinModeling);
    // 设置移动的距离向量
    admMoveFaceBuilder1->Motion()->SetDistanceVector(direction1);
          
    //设置被移动的面
    vector<NXOpen::Face*> nxfaces;
    for (const tag_t& fs : faces)
    {
        NXOpen::Face* face(dynamic_cast<NXOpen::Face*>(NXObjectManager::Get(fs)));
        nxfaces.push_back(face);
    }
    NXOpen::FaceDumbRule* faceDumbRule1;
    faceDumbRule1 = workPart->ScRuleFactory()->CreateRuleFaceDumb(nxfaces);
    std::vector<NXOpen::SelectionIntentRule*> rules1(1);
    rules1[0] = faceDumbRule1;
    admMoveFaceBuilder1->FaceToMove()->FaceCollector()->ReplaceRules(rules1, false);

    // 设置移动距离的值为3.1415
    admMoveFaceBuilder1->Motion()->DistanceValue()->SetRightHandSide(to_string(dis).c_str());

    // 提交AdmMoveFaceBuilder，创建移动特征
    NXOpen::NXObject* nXObject1;
    nXObject1 = admMoveFaceBuilder1->Commit();
    // 销毁AdmMoveFaceBuilder
    admMoveFaceBuilder1->Destroy();

    // 返回移动特征
    return nXObject1->Tag();
}

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

    vector<tag_t> faces = SelectFaces(); //被移动的面
    double dir[] = { 0,0,-1 }; //移动方向
    double dis = 3.14;  //移动距离
    tag_t  moveFaceTag = CreateMoveFaceFeat(faces, dir, dis);

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

#### 代码解析
> 未找到解析内容

