### UGNX二次开发 创建轮廓曲线 UF_CURVE_create_shadow_outline

#### 代码

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;

void CreateShadowOutline(vector<tag_t> bodys)
{
	if (bodys.empty())
		return;

	double tols[2];
	UF_MODL_ask_distance_tolerance(&tols[0]);
	UF_MODL_ask_angle_tolerance(&tols[1]);

	tag_t part = UF_PART_ask_display_part();
	tag_t workPart = UF_ASSEM_ask_work_part();

	if (workPart != part)
		UF_CALL(UF_ASSEM_set_work_part(part));

	tag_t workView;
	UF_CALL(UF_VIEW_ask_work_view(&workView));

	UF_UNDO_mark_id_t markId;
	UF_CALL(UF_UNDO_set_mark(UF_UNDO_visible, "CreateShadowOutlinesLiHai", &markId));

	int solidsCount = bodys.size();

	int* loop_counts;
	int  n_loops;
	tag_t ** curves;
	UF_CALL(UF_CURVE_create_shadow_outline(solidsCount, bodys.data(), workView, &n_loops, &loop_counts, &curves, tols));

	UF_free(curves);
}



void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	vector<tag_t> bodys = SelectBodies();
	CreateShadowOutline(bodys);

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

