### UGNX二次开发 获取圆锥面的矢量

#### 代码

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;

std::array<double, 3> GetFaceDir_lihai(tag_t face)
{
	int type = 0;
	int norm_dir = 0;
	double point[3];
	double dir[3];
	double box1[6];
	double radius;
	double rad_data;
	UF_MODL_ask_face_data(face, &type, point, dir, box1, &radius, &rad_data, &norm_dir);
	return  { dir[0], dir[1], dir[2] };
}


void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	tag_t face = SelectFace();
	std::array<double, 3> dir = GetFaceDir_lihai(face);

	double origin[] = { 0.0,0.0,0.0 };
	UF_DISP_conehead(UF_DISP_ALL_ACTIVE_VIEWS, origin, dir.data(), 0);


	UF_terminate(); 
}


int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY); 
}

```

#### 代码解析
> 未找到解析内容

