### UGNX二次开发 求点沿矢量到某曲线的距离

#### 代码

```cpp
double MW_ask_DIS_ptp(double p1[3], double p2[3])
{
	double DIS = 0.0;
	UF_VEC3_distance(p1, p2, &DIS);
	return DIS;
}
double MW_ask_DIS_ptf(double p1[3], tag_t face, double p2[3])//P2 is in the face
{
	double mindist;
	double accuracy;
	double pt[3];
	pt[0] = p2[0]; pt[1] = p2[1]; pt[2] = p2[2];

	UF_MODL_ask_minimum_dist_3(0, NULL_TAG, face, 1, p1, 0, pt, &mindist, p1, p2, &accuracy);
	return mindist;
}
double MW_ask_DIS_ptl(double p1[3], tag_t edge, double p2[3])
{
	double mindist = 50.0;//用于输出;初始值为100

	double ctol = 0.0;//I//弦长
	double atol = 0.0;//I//角度
	double stol = 2.0;//I//步长
	int numpts = 0;//O//点数
	double* pts = NULL;//O//点集
	int a =UF_MODL_ask_curve_points(edge, ctol, atol, stol, &numpts, &pts);

	double each_pt[3] = {0.0,0.0 ,0.0 };
	double that_dis = 0.0;
	for (int i = 0; i < numpts; i++)
	{
		for (int j = 0; j < 3; j++)
		{
			each_pt[j] = pts[3 * i + j];

		}
		that_dis = MW_ask_DIS_ptp(each_pt,p1);
		ECHO(that_dis); ECHO();
		if (mindist>that_dis)
		{
			mindist = that_dis;
			p2[0] = each_pt[0];
			p2[1] = each_pt[1];
			p2[2] = each_pt[2];
		}
	}
	UF_free(pts);
	return mindist;
}

	//输入点、线、方向
double MW_ask_DIS_ptl(
	double p1[3], //I
	tag_t edge,//I
	double direction[3],//I
	double p2[3] //O
	)//p1是点，dir是方向，edge是目标线，p2是近似交点
{
	double mindist=100.0;//用于输出;初始值为100
	//dir向量单位化
	double mo1;
	double unit_direc[3] = {0.0,0.0, 0.0};
	UF_VEC3_unitize(direction,0.01,&mo1,unit_direc);
	//离散曲线为点
	double ctol=0.0;//I//弦长
	double atol=0.0;//I//角度
	double stol=2.0;//I//步长
	int numpts = 0;//O//点数
	double* pts = NULL;//O//点集
	
	int edge_type=0;
	//UF_MODL_ask_edge_type(edge, &edge_type);
	UF_MODL_ask_curve_points(edge,ctol,atol,stol,&numpts,&pts);

	double each_pt[3];
	double vec2[3];
	double mo2;
	double unit_vec2[3];	
	double dot_product=0.0;
	double that_dis = 0.0;
	for (int i = 0; i < numpts; i++)
	{
		for (int j = 0; j < 3; j++)
		{
			each_pt[j] = pts[3 * i + j];
			vec2[j] = each_pt[j] - p1[j];

		}
		UF_VEC3_unitize(vec2, 0.01, &mo2, unit_vec2);
	
		UF_VEC3_dot(unit_direc,unit_vec2,&dot_product);
		if (dot_product>0.98)//两个向量夹角的cos值
		{
			tag_t pt;
			UF_CURVE_create_point(each_pt,&pt);
			that_dis=MW_ask_DIS_ptp(each_pt,p1);
			if (mindist>that_dis)
			{
				mindist = that_dis;
			}
		}
	}
	return mindist;//if mindist==100.0,曲线在dir方向交点在100mm外或者无交点，如果需要直接测与曲线之间的距离

		/*if (true)
	{

	}
	UF_EVAL_is_line();
	UF_CLEAR_ask_analysis_mode();
	PK_CURVE_ask_edges();
	double vert1[3]; double vert2[3]; int ver_count = 0;
	UF_MODL_ask_edge_verts(line, vert1, vert2, &ver_count);
	double vec1[3]; double vec2[3];

	vec1[0] = direction[0];
	vec1[1] = direction[1];
	vec1[2] = direction[2];
	vec2[0] = vert2[0] - vert1[0];
	vec2[1] = vert2[1] - vert1[1];
	vec2[2] = vert2[2] - vert1[2];

	double dis = 0.0;

	double unit_vec1[3];
	double vec1_mo;
	double unit_vec2[3];
	double vec2_mo;
	UF_VEC3_unitize(vec1, 0.01, &vec1_mo, unit_vec1);
	UF_VEC3_unitize(vec2, 0.01, &vec2_mo, unit_vec2);


	dis = MW_ask_DIS_ptl(p1, line, p2);
	double dot_product=0.0;
	UF_VEC3_dot(unit_vec1, unit_vec2, &dot_product);
	if (dot_product<0.01)
	{
		return dis;
	}
	dis = dis / dot_product;
	if (dis>=0)
	{return dis;

	}
	else
	{
		return -dis;
	}*/
}

```

#### 代码解析
> 未找到解析内容

