### [UFUN函数] UG二次开发，设置渲染样式，如带边着色、静态线框等

#### 代码

```cpp
//设置渲染样式
#include <uf_defs.h>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/ModelingView.hxx>
#include <NXOpen/ModelingViewCollection.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/View.hxx>
#include <uf_ui.h>
using namespace NXOpen;

extern "C" DllExport int ufusr_ask_unload()
{
	return (int)Session::LibraryUnloadOptionImmediately;
}

extern "C" DllExport void ufusr(char *param, int *retCode, int paramLen)
{
	Session *theSession = Session::GetSession();
	Part *workPart(theSession->Parts()->Work());

	//WorkView 工作视图   //SetRenderingStyle 设置视图样式
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeShadedWithEdges);  //带边着色 
	uc1601("带边着色",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeShaded);           //着色
	uc1601("着色",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeWireframeWithDimEdges);  //带有淡化边的线框
	uc1601("带有淡化边的线框",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeWireframeWithHiddenEdges);  //带有隐藏边的线框
	uc1601("带有隐藏边的线框",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeWireframeWithDashedEdges);  //带有虚线边的线框
	uc1601("带有虚线边的线框",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeStudio);                    //艺术外观
	uc1601("艺术外观",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeFaceAnalysis);    //面分析
	uc1601("面分析",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypeStaticWireframe); //静态线框
	uc1601("静态线框",1);

	
	workPart->ModelingViews()->WorkView()->SetRenderingStyle(View::RenderingStyleTypePartiallyShaded); //局部着色
	uc1601("局部着色",1);
}

```

#### 代码解析
> 未找到解析内容

