### UGNX二次开发 获取一个矢量于WCS三个轴的角度

#### 代码

```cpp
#include "me.hpp"
using namespace LiHai;
using namespace std;
using namespace NXOpen;



void GetAngleBetweenWCS(double vec[],double &xAngle, double& yAngle, double& zAngle)
{
	tag_t wcs;
	UF_CSYS_ask_wcs(&wcs);

	tag_t wcsMx;
	double origin[3];
	UF_CSYS_ask_csys_info(wcs, &wcsMx, origin);

	double axes[9];
	UF_CSYS_ask_matrix_values(wcsMx, axes);

	double vec3[3] = { 0.0,0.0,0.0 };
	UF_VEC3_angle_between(vec, &axes[0], vec3, &xAngle);
	UF_VEC3_angle_between(vec, &axes[3], vec3, &yAngle);
	UF_VEC3_angle_between(vec, &axes[6], vec3, &zAngle);

	xAngle = xAngle / PI * 180;
	yAngle = yAngle / PI * 180;
	zAngle = zAngle / PI * 180;

	return;
}


void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

	double vec[] = { 1.0, 1.0, 0 };
	double xAngle = 0.0;
	double yAngle = 0.0;
	double zAngle = 0.0;
	GetAngleBetweenWCS(vec, xAngle, yAngle, zAngle);
	print(xAngle);
	print(yAngle);
	print(zAngle);
		
	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}

```

#### 代码解析
> 未找到解析内容

