### UGNX二次开发 获取拉伸的一些信息 UF_MODL_ask_extrusion

#### 代码

```cpp
#include "me.hpp"
#undef CreateDialog

using namespace NXOpen;
using namespace std;


tag_t AskExtrusion(const tag_t& extrusionFeatureTag)
{
    logical
        region_specified,
        solid_creation;
    int
        n_objects = 0;
    tag_t
        * objects = NULL;
    double
        direction[3] = { 0.0, 0.0, 1.0 },
        region_point[3] = { 0.0, 0.0, 1.0 };
    char
        * limits[2] = { NULL, NULL },
        * offsets[2] = { NULL, NULL },
        * taper_angle = NULL;
    UF_MODL_SWEEP_TRIM_object_p_t
        trim_ptr;
    UF_MODL_ask_extrusion(extrusionFeatureTag, &n_objects, &objects,
        &trim_ptr, &taper_angle, limits, offsets, region_point,
        &region_specified, &solid_creation, direction);

   LiHai::print(n_objects); 

   if (n_objects > 0) UF_free(objects);
   if (trim_ptr != NULL)
   {

       if (trim_ptr->trim_count > 0) UF_free(trim_ptr->trim_objects);
       if (trim_ptr->num_thru_bodies > 0) UF_free(trim_ptr->thru_bodies);
   }
   UF_free(taper_angle);
   UF_free(limits[0]);
   UF_free(limits[1]);
   UF_free(offsets[0]);
   UF_free(offsets[1]);
   
   return null_tag;
}

void ufusr(char* param, int* retcode, int paramLen)
{
	UF_initialize();

    tag_t extrusionFeatureTag = LiHai::SelectFeat();
    AskExtrusion(extrusionFeatureTag);
     

	UF_terminate();
}

int ufusr_ask_unload(void)
{
	return (UF_UNLOAD_IMMEDIATELY);
}


```

#### 代码解析
> 未找到解析内容

