### [UFUN函数] UG二次开发，通过UF_MODL_create_cylinder，创建一个简单的圆柱

#### 代码

```cpp
//创建圆柱
#include <uf.h>
#include <uf_ui.h>
#include <uf_ui_ugopen.h>
#include <uf_modl_primitives.h>
extern "C" DllExport int ufusr_ask_unload()
{
	return (UF_UNLOAD_IMMEDIATELY); 
}

extern "C" DllExport void ufusr(char *param, int *retCode, int paramLen)
{
	UF_initialize();
	UF_FEATURE_SIGN sign=UF_NULLSIGN;//布尔方式 ： 布尔 无
	//UF_NULLSIGN    //布尔 无
	//UF_POSITIVE    //布尔 求和
	//UF_NEGATIVE    //布尔 求差
	//UF_UNSIGNED    //布尔 求交
	double dPoint1[3]={0,0,0};    //圆柱底面圆心
	char charH[256]="10000";      //第一次做圆柱的高度
	char charD[256]="10";        //直径
	double dVector[3]={0,0,1};   //圆柱方向
	tag_t  tagCylinderTemp=NULL_TAG;  //圆柱特征标签
	UF_MODL_create_cylinder(sign,NULL_TAG,dPoint1,charH,charD,dVector,&tagCylinderTemp);
	UF_terminate();
}
```

#### 代码解析
> 未找到解析内容

