### NX二次开发 Block UI 选择对象

#### 代码

```cpp
//方式1
selection0->SetSelectModeAsString("Single"); //单选
selection0->SetSelectModeAsString("Multiple"); //多选
//方式2
selection0->GetProperties()->SetEnum("SelectMode", 0);//单选
selection0->GetProperties()->SetEnum("SelectMode", 1);//多选
```

```cpp
selection0->GetProperties()->SetEnum("MaximumScope", 3); //整个装配
selection0->GetProperties()->SetEnum("MaximumScope", 10); //仅工作部件内
selection0->GetProperties()->SetEnum("MaximumScope", 11); //在工作部件和组件内

selection0->SetMaximumScopeAsString("Entire Assembly"); //整个装配
```

```cpp
//设置过滤的方式
SelectionActionEnableAll //在选择中包含对象
SelectionActionEnableSpecific //在选择中包括选定的对象
SelectionActionDisableSpecific //从选择中删除选定的对象
SelectionActionClearAndEnableSpecific //清除选择并包括选定的对象
SelectionActionAllAndDisableSpecific //选择除已选对象外的所有对象

//设置对象选择过滤，只能选组件
std::vector< NXOpen::Selection::MaskTriple > maskTriple;
Selection::MaskTriple mask1(UF_component_type, 0, 0);
maskTriple.push_back(mask1);
selection0->GetProperties()->SetSelectionFilter("SelectionFilter", Selection::SelectionActionClearAndEnableSpecific, maskTriple);
//或者 selection0->SetSelectionFilter(Selection::SelectionActionClearAndEnableSpecific, maskTriple);

//设置对象选择过滤，只能选体上的面
std::vector< NXOpen::Selection::MaskTriple > maskTriple1;
Selection::MaskTriple mask1(UF_face_type, 0, 0);
maskTriple1.push_back(mask1);
selection0->GetProperties()->SetSelectionFilter("SelectionFilter", Selection::SelectionActionClearAndEnableSpecific, maskTriple1);

//设置对象选择过滤，只能选体上的圆柱面
std::vector< NXOpen::Selection::MaskTriple > maskTriple;
Selection::MaskTriple mask1(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_CYLINDRICAL_FACE);
maskTriple.push_back(mask1);
selection0->GetProperties()->SetSelectionFilter("SelectionFilter", Selection::SelectionActionClearAndEnableSpecific, maskTriple);

//设置对象选择过滤，只能选基准坐标
std::vector< NXOpen::Selection::MaskTriple > maskTriple;
Selection::MaskTriple mask1( UF_coordinate_system_type, 0, 0);
maskTriple.push_back(mask1);
selection0->GetProperties()->SetSelectionFilter("SelectionFilter", Selection::SelectionActionClearAndEnableSpecific, maskTriple);

//设置对象选择过滤，只能选片体
std::vector< NXOpen::Selection::MaskTriple > maskTriple;
Selection::MaskTriple mask1(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_SHEET_BODY);
maskTriple.push_back(mask1);
selection0->GetProperties()->SetSelectionFilter("SelectionFilter", 
Selection::SelectionActionClearAndEnableSpecific, maskTriple);
 
//设置对象选择过滤，只能选实体
std::vector< NXOpen::Selection::MaskTriple > maskTriple1;
Selection::MaskTriple mask2(UF_solid_type, UF_solid_body_subtype, UF_UI_SEL_FEATURE_SOLID_BODY);
maskTriple1.push_back(mask2);
selection01->GetProperties()->SetSelectionFilter("SelectionFilter", 
Selection::SelectionActionClearAndEnableSpecific, maskTriple1);
```

```cpp
selection0->AddFilter(UF_component_type, 0, 0);//type subtype solidBodyType 
```

```cpp
selection0->GetProperties()->SetLogical("AutomaticProgression", false);
```

```cpp
selection0->Focus(); //设置焦点
```

```cpp
vector<tag_t>vecSelectObjects;
std::vector<TaggedObject*>objects = this->selection0->GetProperties()->GetTaggedObjectVector("SelectedObjects");
for (int i = 0; i < objects.size(); i++)
{
    vecSelectObjects.push_back(objects[i]->Tag());
}
```

```cpp
vector< NXOpen::TaggedObject * > objectVector;
objectVector.clear();
this->selection0->SetSelectedObjects(objectVector);
```

```cpp
vector< NXOpen::TaggedObject * > objectVector;
for (int i = 0; i < vecSelected.size(); i++)
{
	NXOpen::TaggedObject* OBJ = dynamic_cast<NXOpen::TaggedObject*>(NXObjectManager::Get(vecSelected[i]));
	objectVector.push_back(OBJ);
}
this->selection0->SetSelectedObjects(objectVector);
```

```cpp
this->selection0->GetProperties()->SetLogical("Show", false); //设置是否显示
this->selection0->GetProperties()->SetString("LabelString", "选择体"); //设置文字
this->selection0->GetProperties()->SetString("Bitmap", "select_body"); //设置图标
```

#### 代码解析
> 未找到解析内容

